"""add product price effective dates

Revision ID: 49766a32e9a7
Revises: 192aefe95ec0
Create Date: 2025-02-07 18:28:44.520500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49766a32e9a7'
down_revision: Union[str, None] = '192aefe95ec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('effective_from', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('effective_to', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'effective_to')
    op.drop_column('products', 'effective_from')
    # ### end Alembic commands ###
