"""update_status_fields_to_string

Revision ID: 7496f96ecb51
Revises: merge_heads
Create Date: 2025-03-30 09:10:54.188494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7496f96ecb51'
down_revision: Union[str, None] = 'merge_heads'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'status',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('companies', 'status',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('countries', 'status',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('ports', 'status',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.add_column('product_history', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('product_history', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('product_history', sa.Column('history_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('product_history', 'product_name_en',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('product_history', 'status',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.drop_column('product_history', 'changed_at')
    op.drop_column('product_history', 'changed_by')
    op.drop_column('product_history', 'change_type')
    op.alter_column('products', 'product_name_en',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('products', 'status',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_products_code'), 'products', ['code'], unique=True)
    op.create_index(op.f('ix_products_product_name_en'), 'products', ['product_name_en'], unique=False)
    op.alter_column('ships', 'status',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('suppliers', 'status',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suppliers', 'status',
               existing_type=sa.String(length=20),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.alter_column('ships', 'status',
               existing_type=sa.String(length=20),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.drop_index(op.f('ix_products_product_name_en'), table_name='products')
    op.drop_index(op.f('ix_products_code'), table_name='products')
    op.alter_column('products', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('products', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('products', 'status',
               existing_type=sa.String(length=20),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.alter_column('products', 'product_name_en',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.add_column('product_history', sa.Column('change_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('product_history', sa.Column('changed_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('product_history', sa.Column('changed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('product_history', 'status',
               existing_type=sa.String(length=20),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.alter_column('product_history', 'product_name_en',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('product_history', 'history_date')
    op.drop_column('product_history', 'updated_at')
    op.drop_column('product_history', 'created_at')
    op.alter_column('ports', 'status',
               existing_type=sa.String(length=20),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.alter_column('countries', 'status',
               existing_type=sa.String(length=20),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.alter_column('companies', 'status',
               existing_type=sa.String(length=20),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.alter_column('categories', 'status',
               existing_type=sa.String(length=20),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    # ### end Alembic commands ###
