"""add_order_upload_tables

Revision ID: 98e37707144f
Revises: 30e27edaa6d5
Create Date: 2025-02-09 18:11:40.220818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98e37707144f'
down_revision: Union[str, None] = '30e27edaa6d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=True),
    sa.Column('order_no', sa.String(length=50), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('ship_code', sa.String(length=50), nullable=True),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('supplier_info', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['order_uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_orders_id'), 'upload_orders', ['id'], unique=False)
    op.create_table('upload_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_code', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['upload_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_order_items_id'), 'upload_order_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upload_order_items_id'), table_name='upload_order_items')
    op.drop_table('upload_order_items')
    op.drop_index(op.f('ix_upload_orders_id'), table_name='upload_orders')
    op.drop_table('upload_orders')
    # ### end Alembic commands ###
